apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: quantranvan-pod
  template:
    metadata:
      labels:
        app: quantranvan-pod
    spec:
      containers:
        - name: eks-nodejs-test
          image: quanbb/eks-nodejs-test:1.0
          ports:
            - containerPort: 3000
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - nc -z localhost 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            initialDelaySeconds: 30
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              memory: '128Mi'
              cpu: '500m'
            limits:
              memory: '500Mi'
              cpu: '1000m' #equal to 1 core CPU