apiVersion: v1
kind: Service
metadata:
  name: quantranvan-service
spec:
  type: NodePort
  selector:
    app: quantranvan-pod
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30001